apiVersion: v1
kind: Service
metadata:
  name: svc-back-ventas
  namespace: innovatech-production
spec:
  type: ClusterIP
  selector:
    app: back-ventas
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080