apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-despachos
  namespace: innovatech-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-despachos
  template:
    metadata:
      labels:
        app: back-despachos
    spec:
      containers:
      - name: back-despachos
        image: 193318341091.dkr.ecr.us-east-1.amazonaws.com/back-despachos:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"