name: CI/CD Backends EKS

on:
  push:
    branches: [ main ]
    paths:
      - 'back-Ventas_SpringBoot/**'
      - 'back-Despachos_SpringBoot/**'

env:
  ECR_REPO_BACKEND_1: back-ventas
  ECR_REPO_BACKEND_2: back-despachos

jobs:
  build-and-deploy-backends:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
      - name: Build & push
        env:
          REG: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd back-Ventas_SpringBoot && docker build -t $REG/${{ env.ECR_REPO_BACKEND_1 }}:${{ env.IMAGE_TAG }} . && docker push $REG/${{ env.ECR_REPO_BACKEND_1 }}:${{ env.IMAGE_TAG }}
          cd ../back-Despachos_SpringBoot && docker build -t $REG/${{ env.ECR_REPO_BACKEND_2 }}:${{ env.IMAGE_TAG }} . && docker push $REG/${{ env.ECR_REPO_BACKEND_2 }}:${{ env.IMAGE_TAG }}

      - name: Actualizar manifests con tag
        run: |
          sed -i "s|\${IMAGE_TAG}|${{ env.IMAGE_TAG }}|g" k8s/back-ventas-deployment.yaml
          sed -i "s|\${IMAGE_TAG}|${{ env.IMAGE_TAG }}|g" k8s/back-despachos-deployment.yaml

      - name: Configurar kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ECK_PRUEBA3

      - name: Aplicar y actualizar despliegues
        run: |
          kubectl apply -f k8s/